### ISSUE TITLE
where is the sql database

### ISSUE THREAD

**Issue by aditya5660** [NeymarJohn/QMS-Quality_Management_System-#1]
where is the sql database?

**Comment by NeymarJohn** [comment]
Hey who are you?

**Comment by aditya5660** [comment]
I find this repo from GitHub search

**Comment by NeymarJohn** [comment]
No this is not open source project

**Comment by graham3767** [comment]
Hi Sunriver,

We have only forked the original project.  We are not the author.

Programmer and author here  https://github.com/NeymarJohn

https://github.com/NeymarJohn/QMS-Quality_Management_System-

We also had the same question about the Database, with no luck.

We wish you the best in finding it.

**Comment by NeymarJohn** [comment]
This is big system and I can't share the database with you.
Sorry for that.
Anyway I hope you can do it with alone.
